# Generated by Django 5.0.4 on 2024-04-16 13:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movierecommendation', '0003_weiboentry'),
    ]

    operations = [
        migrations.CreateModel(
            name='WeiboEntryIndex',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('keyword', models.CharField(max_length=256, verbose_name='关键词')),
                ('doclist', models.TextField(verbose_name='文档列表')),
            ],
            options={
                'verbose_name': '微博索引',
                'verbose_name_plural': '微博索引',
            },
        ),
    ]
