# Generated by Django 5.0.4 on 2024-04-16 13:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('movierecommendation', '0004_weiboentryindex'),
    ]

    operations = [
        migrations.DeleteModel(
            name='WeiboEntry',
        ),
        migrations.DeleteModel(
            name='WeiboEntryIndex',
        ),
    ]
